### ISSUE TITLE
Seattle JS community happy hour (Monday, 8/17)

### ISSUE THREAD

**Issue by crtr0** [cascadiajs/cjs-meatspace#2]
* **When:** Monday, 8/17 @ 5:30pm
* **Where:** Radiator Whiskey
* **Why:** [Mikeal's in town!](https://twitter.com/mikeal/status/628649970468454400)

To RVSP, please leave a comment below. If you have suggestions on **places to eat** or **places to drink**, let me know.

**Comment by jefflembeck** [comment]
I'm in.

**Comment by alexlande** [comment]
:octopus::evergreen_tree:

**Comment by KatieK2** [comment]
I'm in!

Suggestion: The Pike Brewing company - downtown; has a large and flexible bar area.

**Comment by ellist** [comment]
I'm in

**Comment by toddself** [comment]
happy to join

**Comment by YiddishNinja** [comment]
Count me in.
![forcie](https://cloud.githubusercontent.com/assets/10713246/9093396/c985c73e-3b60-11e5-812c-622b9137c680.jpg)

**Comment by davethegr8** [comment]
iiinnnnn

**Comment by DeirdreAllison** [comment]
I'm in! +1 for Pike

**Comment by codefoster** [comment]
Oh, fine. I'll go.

**Comment by dustyjewett** [comment]
I'm In!

**Comment by simplesthing** [comment]
In

**Comment by blakmatrix** [comment]
A comment below.

**Comment by crtr0** [comment]
Ok, @alexlande and I have booked 2 tables (one for 6, one for 4) at Radiator Whiskey for 5:30pm. If anyone else would like to book another table (OpenTable) I'm sure we could fill it. See you all there!

**Comment by crtr0** [comment]
Hey everyone!

Please plan on being a Radiator Whiskey no later than 5:30pm. If you can't make it, please leave a comment and let us know. We've reserved 3 tables for a capacity of 14 people, which accommodates everyone on this issue :)

**Comment by jefflembeck** [comment]
Hey,

No way I can make it out before putting the kiddo down. Any chance folks will be continuing after 8?

**Comment by codefoster** [comment]
I feel like some bourbon will resolve this issue.

**Comment by jefflembeck** [comment]
I mean, she's only 1, but yeah, I can probably get her to sleep by 5 with some bourbon

**Comment by codefoster** [comment]
Haha... I meant the overall GitHub issue, but whatever works :)

**Comment by YiddishNinja** [comment]
I'll be there by 5:30, but leaving by 8. My kiddos are older, bedtime story
time starts at 9, and Harry just met Ron on the Hogwarts Express last
night. Hermione awaits.

**Comment by toddself** [comment]
This some how magically fell on a night where my wife is taking our kids to her parent's house for the northwest washington fair.

a little sad that this place doesn't have elephant ears...

**Comment by ellist** [comment]
Extremely bummed that I can't come tonight. Longstanding appointment that I completely spaced on. PLEASE Happy hour again! :)

**Comment by jefflembeck** [comment]
Scratch my earlier comment. 5:30 it is. :smile: 

See y'all there!

**Comment by crtr0** [comment]
I'll be at Radiator Whiskey around 5:20pm. Look for the guy in cargo shorts and a green CascadiaJS Browser Day t-shirt!

**Comment by YiddishNinja** [comment]
"Look for the guy in cargo shorts and a green CascadiaJS Browser Day
t-shirt!"

Because no one would recognize you otherwise? :-)

I'l start the trek from 2nd and Seneca around 5:15 and should be there
within minutes. I'm wearing jeans and a t-shirt with a Doge/Dr. Who mash-up.

- Greg

**Comment by toddself** [comment]
I'm in the libuv dinocorn shirt.

heading down from boylston and pine in a few minutes
